<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>io.valkey.springframework</groupId>
	<artifactId>spring-data-valkey-parent</artifactId>
	<version>0.1.0</version>
	<packaging>pom</packaging>

	<name>Spring Data Valkey Parent</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<mockito>5.14.2</mockito>
		<cdi>4.1.0</cdi>
		<webbeans>4.0.3</webbeans>
		<kotlin-coroutines>1.9.0</kotlin-coroutines>
		<mockk>1.13.13</mockk>
		<awaitility>4.2.2</awaitility>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.data.build</groupId>
				<artifactId>spring-data-parent</artifactId>
				<version>3.5.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<modules>
		<module>spring-data-valkey</module>
		<module>spring-boot-starter-data-valkey</module>
		<module>examples</module>
		<module>performance</module>
	</modules>

</project>
